name: 'Comment on PR'
description: 'Comment on a PR when it is created.'
inputs:
  repo-token:  # id of input
    description: 'Token for GitHub repo'
    required: true
  comment: 
    description: 'The comment to leave'
    required: false
    default: 'This is the default comment'
runs:
  using: 'node12'
  main: 'dist/index.js'