name: 'Bufferbot Helper'
description: 'Your helpful GitHub Actions bot for Buffer deployments.'
inputs:
  repo-token:
    description: 'Token for GitHub'
    required: true
  staging-url-template:
    description: 'Staging URL string with a `{{placeholder}}` for the formatted branch name.'
    required: true
  service-name:
    description: 'The name of the service as used in deployment keys. Usually the name of the repository. E.g., "buffer-publish"'
    required: true
  action:
    description: 'The action to perform. Defaults to "pr-comment" which posts a comment on PRs with links/context. Can also be "get-staging-url-when-deployed" to return staging URL for further use in the workflow. See the README.md for more details.'
    required: false
    default: 'pr-comment'
outputs:
  stagingUrl:
    description: 'The staging URL of the deployment when it has been completed. Only returned when the input action is "get-staging-url-when-deployed"'
runs:
  using: 'node12'
  main: 'dist/index.js'