name: 'Bufferbot Helper'
description: 'Comments on new PRs with helpful links.'
inputs:
  repo-token:
    description: 'Token for GitHub'
    required: true
  staging-url-template:
    description: 'Staging URL string with a `{{placeholder}}` for the formatted branch name.'
    required: true
  service-name:
    description: 'The name of the service as used in deployment keys. Usually the name of the repository. E.g., "buffer-publish"'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'